### ISSUE TITLE
Bot commands

### ISSUE THREAD

**Issue by bkil** [jjj333-p/spam-police#11] opened 2022-09-09 11:16 UTC
The bot could be controlled by slash commands in a designated room and/or by whoever invited it and/or from whichever room it was sent from there.

`!police modmention false`
or `!police modmention #room:example.com false`

**Comment by jjj333-p** [comment] 2022-09-09 11:18
sorta a duplicate of #3, and i specifically designed the bot to not require a designated room because i see that as the major flaw with mjolnir

**Closed by jjj333-p** 2022-09-09 11:18 UTC
