### ISSUE TITLE
Option to disable mod mentions

### ISSUE THREAD

**Issue by bkil** [jjj333-p/spam-police#12] opened 2022-09-09 11:17 UTC
We sometimes invite it to rooms that are abandoned. These are very good inputs to the scam detector, but it makes no sense to mention "mods" if there is nobody there. The current workaround is if a mod mutes the whole room completely, which is not ideal.

It might be a good idea to have options to set this via #11

**Comment by jjj333-p** [comment] 2022-09-09 11:19
duplicate of #3 in a way

**Closed by jjj333-p** 2022-09-09 11:19 UTC
